Working as intended

diff --git a/coreboot b/coreboot
--- a/coreboot
+++ b/coreboot
@@ -171,7 +171,7 @@ no_prohibited_process() {
     PROC_FOUND=0
     IFS=',' read -ra PROC_LIST <<< "${CONFIG[PREVENT_PROCESSES]}"
     for PROC in "${PROC_LIST[@]}"; do
-        pgrep -f "${PROC}"
+        pgrep -f "${PROC}" > /dev/null
         if [[ $? -eq 0 ]]; then
             PROC_FOUND=1
             break
@@ -220,6 +220,12 @@ check_reboot() {
         no_active_users; then
             _debug "All reboot checks passed!"
             REBOOT_OKAY=1
+    elif [[ ${IS_TTY} -eq 0 ]]; then
+        echo "FAILURE: It is not currently safe to reboot."
+        if [[ ${CONFIG[DELAY_UNTIL_OKAY]} -eq 1 ]]; then
+            echo "To schedule a reboot for once it is safe, run:  systemd start coreboot"
+        fi
+        exit 7
     fi
 }
 
